default_platform(:ios)

platform :ios do
  desc 'Build a release version of the framework'
  lane :clean_release_build do
    xcodebuild(
      scheme: 'RASqlite',
      configuration: 'Release',
      clean: true,
      build: true,
      build_settings: [['ONLY_ACTIVE_ARCH', 'NO']]
    )
  end
end
